[project]
name = "hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytubefix>=8.8.2",
    "jupyter-ai>=2.28.4",
    "jupyter>=1.1.1",
]
